name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd packages/html && npm install
      - run: cd packages/html && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
